"""add initial models

Revision ID: 75678dcb99b9
Revises: 
Create Date: 2023-05-16 01:30:50.227662

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "75678dcb99b9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("node_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_channels_node_id"), "channels", ["node_id"], unique=False)
    op.create_table(
        "members",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("node_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_members_node_id"), "members", ["node_id"], unique=False)
    op.create_index(op.f("ix_members_user_id"), "members", ["user_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.String(length=4096), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_author_id"), "messages", ["author_id"], unique=False)
    op.create_index(op.f("ix_messages_channel_id"), "messages", ["channel_id"], unique=False)
    op.create_table(
        "nodes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nodes_owner_id"), "nodes", ["owner_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("password_salt", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_nodes_owner_id"), table_name="nodes")
    op.drop_table("nodes")
    op.drop_index(op.f("ix_messages_channel_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_author_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_members_user_id"), table_name="members")
    op.drop_index(op.f("ix_members_node_id"), table_name="members")
    op.drop_table("members")
    op.drop_index(op.f("ix_channels_node_id"), table_name="channels")
    op.drop_table("channels")
    # ### end Alembic commands ###
